version: "3.7"

services:
    mongodb_container:
        image: mongo:latest
        environment:
            MONGO_INITDE_ROOT_USERNAME: root
            MONGO_INITDE_ROOT_PASSWORD: password ports
        ports:
        - 27017:27017
        volumes:
        - mongodb_data_container:/data/db

volumes:
mongodb_data_container:
